// Weapon sfx. On real hardware AthenaEnv provides the Sound module (audsrv
// ADPCM, enabled in athena.ini); in the browser src/web/ps2-scene.ts installs
// a Phaser-backed shim with the same shape. Every entry point no-ops when the
// host lacks the API, so the game still runs silent. Rumble lives in
// lib/haptics.js.

const HAS_SFX = typeof Sound !== 'undefined' && typeof Sound.Sfx === 'function';

// role name -> playback volume (0-100); files live at assets/sfx/<name>.adp
// (.wav twin for the browser), generated by scripts/prep-assets.py
const BANK = {
  ion_fire: 35,
  ciga_fire: 35,
  pac_fire: 45,
  ion_hit: 25,
  ciga_hit: 25,
  pac_hit: 25,
  dash: 50,
  fireblast: 60,
  switch: 40,
  button_press: 45,
  blood_01: 45,
  blood_02: 45,
};

const MIN_GAP = 0.06; // seconds between plays of the same effect (spam guard)

const bank = {};
let clock = 0; // advanced by tickAudio; drives the per-effect throttle

export function initAudio() {
  if (!HAS_SFX) return;
  for (const name of Object.keys(BANK)) {
    const s = Sound.Sfx(`assets/sfx/${name}.adp`);
    s.volume = BANK[name];
    bank[name] = { s, lastAt: -Infinity };
  }
}

/** call once per frame from the active screen's update */
export function tickAudio(dt) {
  clock += dt;
}

let bloodTake = 0;

/** the blood splat's two takes, alternating — back-to-back kills would sound
    like one sample stuttering otherwise (and each take keeps its own MIN_GAP
    slot, so a fast kill streak still gets a sound per splat) */
export function sfxBlood() {
  sfx(bloodTake++ & 1 ? 'blood_02' : 'blood_01');
}

export function sfx(name) {
  const entry = bank[name];
  if (!entry) return;
  if (clock - entry.lastAt < MIN_GAP) return;
  if (Sound.findChannel() === -1) return; // all 24 ADPCM channels busy
  entry.lastAt = clock;
  entry.s.play();
}
