#!/usr/bin/env python3
"""demos.xml -> ps2/data/demos.js: the attract-mode reel.

Source is the Crimsonland Android rip's demo definitions (menu background
demos + trial upsell demos), copied into scripts/art/demos.xml. Trooper
positions are authored for the original's 1680x1050 world and are scaled
onto this port's fixed 640x448 arena; weapon names are mapped onto the
port's three weapons (data/tuning.js WEAPONS order: ION, CIGA, PAC) by
family — energy weapons fire ION, ballistic sprayers CIGA, scatter/rocket
guns PAC. Attributes prefixed with '_' are disabled in the source and
skipped, matching how the original engine reads them.

  python3 scripts/prep-demos.py
"""

import json
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / "art" / "demos.xml"
OUT = ROOT / "ps2" / "data" / "demos.js"

# original world -> this port's arena
SRC_W, SRC_H = 1680.0, 1050.0
ARENA_W, ARENA_H = 640, 448

# Crimsonland weapon -> WEAPONS index (0 ION, 1 CIGA, 2 PAC)
WEAPON_MAP = {
    "ION_MINIGUN": 0,
    "PLASMA_MINIGUN": 0,
    "PLASMA_RIFLE": 0,
    "PLASMA_OVERLOAD": 0,
    "PLASMA_SHOTGUN": 0,
    "GAUSS_GUN": 0,
    "GAUSS_SHOTGUN": 0,
    "ASSAULT_RIFLE": 1,
    "SUBMACHINE_GUN": 1,
    "MEAN_MINIGUN": 1,
    "MINIGUN": 1,
    "SHOTGUN": 2,
    "SAWED_OFF_SHOTGUN": 2,
    "ROCKET_MINIGUN": 2,
    "ROCKET_LAUNCHER": 2,
}


# upsell lines that only make sense in the original's trial build — the reel
# still plays these nodes, just without the pitch on screen
NO_TEXT = {"TRIAL_DEMO_0", "TRIAL_DEMO_1"}


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


demos = []
for node in ET.parse(SRC).getroot().find("array"):
    a = node.attrib
    troopers = []
    for i in range(1, 5):
        pos = a.get(f"trooper_{i}_position")
        if not pos:
            continue
        x, y = (float(c) for c in pos.split(","))
        troopers.append({
            "x": clamp(round(x * ARENA_W / SRC_W), 40, ARENA_W - 40),
            "y": clamp(round(y * ARENA_H / SRC_H), 40, ARENA_H - 40),
            "weapon": WEAPON_MAP.get(a.get(f"trooper_{i}_weapon", ""), 1),
        })
    demos.append({
        "id": a["id"],
        "duration": float(a["duration"]),
        "spawns": a.get("spawns"),
        "powerups": "WEAPON_POWERUPS" in a.get("tags", ""),
        "text": None if a["id"] in NO_TEXT else a.get("upsell_text"),
        "troopers": troopers,
    })

lines = [
    "// GENERATED by scripts/prep-demos.py from scripts/art/demos.xml — do not",
    "// edit by hand. The Crimsonland demo reel (menu + upsell definitions),",
    "// scaled onto the 640x448 arena; screens/demo.js plays these in order.",
    "export const DEMOS = " + json.dumps(demos, indent=2) + ";",
    "",
]
OUT.write_text("\n".join(lines), encoding="utf-8")
for d in demos:
    print(f"  {d['id']:14s} {d['duration']:4.1f}s  spawns={d['spawns'] or '-':14s} troopers={len(d['troopers'])}")
print(f"[prep-demos] wrote {len(demos)} demos to {OUT}")
