#!/usr/bin/env python3
"""Player-skin assets: pre-rotated sheets for Duke (P1) and Contra's Bill
(P3) / Lance (P4), merged into the generated ps2/data/sheets.js.

Each hero ships as a small top-down walk atlas in scripts/art (4 frames,
gun pointing up = heading -90 deg): duke_atlas is shmup-party-phaser4's
attract-mode hero, bill_atlas/lance_atlas are Contra's commandos. AthenaEnv's
Image API has no rotation, so like prep-assets.py rotations() each walk frame
is baked into 16 pre-rotated directions (22.5 deg steps, frame =
anim * 16 + dir).

Bill and Lance's source art is much smaller than Duke's (23x27 vs 31x48),
so their frames get a 2x nearest-neighbor upscale before rotation to stand
at trooper height on screen.

Runs on repo-local sources only (scripts/art) — prep-assets.py's source
trees aren't needed. Rerun after prep-assets.py regenerates sheets.js:

  python3 scripts/prep-players.py
"""

import json
import math
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "scripts" / "art"
OUT = ROOT / "ps2" / "assets"
SHEETS_JS = ROOT / "ps2" / "data" / "sheets.js"

DIRS = 16  # 360/16 = 22.5 deg, matching util.js dirFrame()

# the blue/green trooper recolors Bill and Lance replaced
STALE = ("player-blue", "player-green")


def atlas_sheet(stem, out_name, upscale=1):
    """16 pre-rotated directions x N walk frames from a scripts/art atlas.
    Frame order follows the atlas's sorted key order (duke_0..3, atlas_s0..3)."""
    atlas = json.loads((ART / f"{stem}.json").read_text())
    img = Image.open(ART / f"{stem}.png").convert("RGBA")
    frames = [atlas["frames"][k]["frame"] for k in sorted(atlas["frames"])]

    # cell must fit the largest upscaled frame's rotation diagonal
    # (duke 31x48 -> 57.2 -> 58; 8 cols keeps every sheet under the GS's
    # 1024px texture limit)
    w = max(f["w"] for f in frames) * upscale
    h = max(f["h"] for f in frames) * upscale
    cell = math.ceil(math.hypot(w, h))
    cols = 8
    rows = math.ceil(len(frames) * DIRS / cols)
    grid = Image.new("RGBA", (cell * cols, cell * rows), (0, 0, 0, 0))

    base_angle = -90  # the source art natively faces up (north)
    for a, f in enumerate(frames):
        crop = img.crop((f["x"], f["y"], f["x"] + f["w"], f["y"] + f["h"]))
        if upscale != 1:
            crop = crop.resize((f["w"] * upscale, f["h"] * upscale), Image.NEAREST)
        canvas = Image.new("RGBA", (cell, cell), (0, 0, 0, 0))
        canvas.paste(crop, ((cell - crop.width) // 2, (cell - crop.height) // 2))
        for d in range(DIRS):
            rot = canvas.rotate(-(d * 22.5 - base_angle), resample=Image.BICUBIC)
            i = a * DIRS + d
            grid.paste(rot, ((i % cols) * cell, (i // cols) * cell))

    grid.save(OUT / f"{out_name}.png")
    return {
        "file": f"assets/{out_name}.png", "fw": cell, "fh": cell,
        "count": len(frames) * DIRS, "cols": cols, "rotated": True,
        "dirs": DIRS, "anim": len(frames),
    }


def merge_sheets(extra):
    txt = SHEETS_JS.read_text(encoding="utf-8")
    start = txt.index("export const SHEETS = ") + len("export const SHEETS = ")
    end = txt.rindex("};")
    sheets = json.loads(txt[start:end + 1])
    sheets.update(extra)
    for k in STALE:
        sheets.pop(k, None)
    lines = [
        "// GENERATED by scripts/prep-assets.py + prep-players.py — do not edit by hand.",
        "// Frame metadata for every animated/rotated sheet in ps2/assets.",
        "export const SHEETS = " + json.dumps(sheets, indent=2, sort_keys=True) + ";",
        "",
    ]
    SHEETS_JS.write_text("\n".join(lines), encoding="utf-8")


# ISO9660-safe basenames; logical skin names match
extra = {
    "duke": atlas_sheet("duke_atlas", "duke"),
    "bill": atlas_sheet("bill_atlas", "bill", upscale=2),
    "lance": atlas_sheet("lance_atlas", "lance", upscale=2),
}

merge_sheets(extra)
for name, meta in sorted(extra.items()):
    print(f"  {name:14s} {meta['fw']}x{meta['fh']} x{meta['count']}")
print(f"[prep-players] wrote duke.png, bill.png, lance.png to {OUT}")
